### ISSUE TITLE
Unstable, not working

### ISSUE THREAD

**Issue by milen-prg** [MalcolmMielle/Semantic-Highlighting#9]
Installed on VSCode, Windows 10 64bit, all updated.

Used in C source of CMAKE project.

When start to edit the source the proper variables coloring appears randomly for several seconds, but after that again they become white.

Can you make the extension to colorize semantically the variables in the source code and keep stable this color util the VSCode closing?

**Comment by MalcolmMielle** [comment]
That's surprising, I use this extension wiht python and C++ and it works well :/. 

Have you tried using it with all other extensions disabled? There might be a conflicting extension.

**Comment by milen-prg** [comment]
I use many extensions and they are necessary for me. I think that the reason is the too high CPU usage from the C/C++ extension, but this is another problem, which have no decision and no alternative (until the CLion became paid). Now I use another highlighter (chaotic and ugly, and heavy, not compared to your's, which is the best), it constantly changes the colors and sometimes even freezes the editor, because of the too high CPU.
At Python for example, the CPU is not used (as the C/C++ extension is not active then) and the colorizers works fine. I think that when there is no CPU resources some glitches appears in whole VSCode. Unfortunately this seems its incurable disease in years.
